#!/bin/bash

all: test

test:
	python RandomVariable.py
	python Uniform.py
	python Beta.py
	python Bernoulli.py
	python Dirichlet.py
	python Categorical.py
	python Gamma.py
	python Gaussian.py

clean:
	rm -rf ./__pycache__

